# Change these first
owner: tavy315 # Your GitHub username
repo: upptime # Your Github repository name

# Add your sites here
sites:
  - name: Webstore
    url: https://www.webstore.be
  - name: Octav.Name
    url: https://www.octav.name
  - name: LG-Imports
    url: https://www.lg-imports.be
  - name: Tracknator
    url: https://www.tracknator.com

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: upptime.octav.name
  # Uncomment the following line if you don't have a custom domain and add your repo name
  #baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: ""
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
